Description:
  IAM Role for ECS
  
Resources:

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsInstanceRole
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ec2.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: ec2-ecs-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: ['ecs:CreateCluster', 'ecs:DeregisterContainerInstance', 'ecs:DiscoverPollEndpoint',
              'ecs:Poll', 'ecs:RegisterContainerInstance', 'ecs:StartTelemetrySession',
              'ecs:Submit*', 'ecr:GetAuthorizationToken', 'ecr:BatchCheckLayerAvailability', 'ecr:GetDownloadUrlForLayer',
              'ecr:BatchGetImage', 'logs:CreateLogStream', 'logs:PutLogEvents']
            Resource: '*'
   
  ECSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsServiceRole
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: ecs-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:        
                   - "ec2:AuthorizeSecurityGroupIngress"
                   - "ec2:Describe*"
                   - "elasticloadbalancing:DeregisterInstancesFromLoadBalancer"
                   - "elasticloadbalancing:DeregisterTargets"
                   - "elasticloadbalancing:Describe*"
                   - "elasticloadbalancing:RegisterInstancesWithLoadBalancer"
                   - "elasticloadbalancing:RegisterTargets"
            Resource: "*"
              
  ECSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref EC2Role

Outputs:
  ECSRole:
    Description: Reference to the ECS Role
    Value: !Ref ECSRole
    
  ECSInstanceProfile:
    Description: Reference to the ECS IAM Role Instance Profile used for ECS Cluster Instances.
    Value: !Ref ECSInstanceProfile